---
php_version: "7.4"
testrail_db_name: "testrail"
testrail_db_user: "testrail"
testrail_db_password: "testrail"
testrail_install_folder: "/var/www/html"
testrail_folder_user: "www-data"
testrail_folder_group: "www-data"
